version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
